### ISSUE TITLE
SpaceX Dashboard Challenge

### ISSUE THREAD

**Issue by ibratnawaz** [nawazibrat/bigbinary-interview-for-nawazibrat#1]
https://public.3.basecamp.com/p/UGEyqrnc11MEXx8ndGmJcA49

**Comment by ibratnawaz** [comment]
Deployed Link:  https://spacex-dashboard-kappa.vercel.app/

**Comment by ibratnawaz** [comment]
The application is ready for the code review.

**Comment by vinay0x** [comment]
Please pick a timeslot for the next phase of your interview process: http://calendly.com/vinaychandranvs/vinay-v-1
